# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Sample(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, bug_text: str=None):  # noqa: E501
        """Sample - a model defined in Swagger

        :param bug_text: The bug_text of this Sample.  # noqa: E501
        :type bug_text: str
        """
        self.swagger_types = {
            'bug_text': str
        }

        self.attribute_map = {
            'bug_text': 'bug_text'
        }
        self._bug_text = bug_text

    @classmethod
    def from_dict(cls, dikt) -> 'Sample':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Sample of this Sample.  # noqa: E501
        :rtype: Sample
        """
        return util.deserialize_model(dikt, cls)

    @property
    def bug_text(self) -> str:
        """Gets the bug_text of this Sample.


        :return: The bug_text of this Sample.
        :rtype: str
        """
        return self._bug_text

    @bug_text.setter
    def bug_text(self, bug_text: str):
        """Sets the bug_text of this Sample.


        :param bug_text: The bug_text of this Sample.
        :type bug_text: str
        """

        self._bug_text = bug_text
